### ISSUE TITLE
java.lang.UnsatisfiedLin kError: \AppData\Local\Temp\librocksdbjni5690556299205306066.dll: Can't find dependent libraries

### ISSUE THREAD

**Issue by sreenivasulun** [simplesteph/kafka-streams-course#12]
Getting the below error, when I ran the words count sample,

INFO stream-thread [wordcount-application-0f0f6e16-c20b-4243-8ae3-9e85c90f8510-StreamThread-1] Stream thread shutdown co
mplete (org.apache.kafka.streams.processor.internals.StreamThread:1072)
WARN stream-thread [wordcount-application-0f0f6e16-c20b-4243-8ae3-9e85c90f8510-StreamThread-1] Unexpected state transiti
on from ASSIGNING_PARTITIONS to DEAD. (org.apache.kafka.streams.processor.internals.StreamThread:978)
Exception in thread "wordcount-application-0f0f6e16-c20b-4243-8ae3-9e85c90f8510-StreamThread-1" java.lang.UnsatisfiedLin
kError: C:\Users\snarasi\AppData\Local\Temp\librocksdbjni5690556299205306066.dll: Can't find dependent libraries
        at java.lang.ClassLoader$NativeLibrary.load(Native Method)
        at java.lang.ClassLoader.loadLibrary0(Unknown Source)
        at java.lang.ClassLoader.loadLibrary(Unknown Source)
        at java.lang.Runtime.load0(Unknown Source)
        at java.lang.System.load(Unknown Source)
        at org.rocksdb.NativeLibraryLoader.loadLibraryFromJar(NativeLibraryLoader.java:78)
        at org.rocksdb.NativeLibraryLoader.loadLibrary(NativeLibraryLoader.java:56)

**Comment by simplesteph** [comment]
From another student:

> I had the same issue. I had to install the "Microsoft Visual C++ 2015 Redistributable". It comes with some dependencies needed by RocksDB (which is also needed by KafkaStreams). Once installed , it works! 

> I was using Windows 8.1, but in order to install the Microsoft Visual C++ 2015, I also needed the Update for Windows - KB2999226. Without this update I was not able to install the C++ dependencies. 

> I hope it helps for windows user
